version: '3'
services:
  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backEnd:/app
    ports:
      - "3333:3333"
    depends_on:
      - postgresql
    command: >
      bash -c "yarn prisma migrate deploy && yarn dev"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgresql:5432/crud
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud
  #  ports:
  #    - "5432:5432"
    
  frontend:
    image: httpd:2.4
    volumes:
      - ./frontEnd/build:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    depends_on:
      - backend

